### ISSUE TITLE
Tailor tool/features to CIME4R features only

### ISSUE THREAD

**Issue by ginihumer** [jku-vds-lab/reaction-cime#12]

**Comment by dvmoritzschoefl** [comment]
As discussed with Christina:
remove unnecessary features that are not relevant for CIME:

- [x] sequence encodings
- [x] projections t-SNE and ForceAtlas2 should be removed
- [x] active line sequence

**Comment by ginihumer** [comment]
note by marc: UI improvements for CIME4R use cases (labels, usability, etc.)

**Comment by Aystein** [comment]
To the best of my knowledge these points are now resolved, the sequence UI will not show anymore when the data itself has no sequences. also all projections are remote now.
