### ISSUE TITLE
background interaction

### ISSUE THREAD

**Issue by ginihumer** [jku-vds-lab/reaction-cime#17]
users should be able to interact with the background (i.e. if they click somewhere on the background, they should get information about the x closest datapoints of this position)
could be done by just adding those datapoints to the "poi" dataset, or we could have some additional view that just lists the information of these points

**Comment by ginihumer** [comment]
I think that this should be doable by only modifying the Reaction-CIME application
the background is rendered in "AggregationLayer.tsx" and "GLHeatmap.tsx" --> have some click event that gives coordinates of the click

the backend is mostly in the "reaction_cime_api.py" file

notes:
"points of interest" (POI) are currently determined in a static way (all points where yield > 0)  --> if we want to add the nearest datapoints to the POIs, we have to make this dynamic

**Comment by CursedSeraphim** [comment]
added first steps for this feature in PR #23
setting k for k-nearest neighbors in aggregation tab panel and clicking a new option in the context menu will download a file containing the nearest neighbors to the click position including the background data which is not visible

still up for discussion what happens next, and whether we want to include PSE functionality to add individual vectors to the currently loaded dataset
