### ISSUE TITLE
Line up doesn't show

### ISSUE THREAD

**Issue by heberleh** [jku-vds-lab/reaction-cime#24]
Load all button after projection doesn't open lineup
*ignore the tooltip arrow in the image
<img width="1486" alt="Screenshot 2022-01-26 at 10 08 24" src="https://user-images.githubusercontent.com/4249107/151136226-16db4343-69d5-43bd-83b1-c02d28bebb10.png">

**Comment by ginihumer** [comment]
@dvmoritzschoefl does this work properly for bayer cime?
pulling lineup up from the bottom seems to work

**Comment by dvmoritzschoefl** [comment]
I can reproduce the issue, this is most likely an issue that the react component is not rendered correctly, I will check the component mounting in PSE

**Comment by ginihumer** [comment]
the problem was some missalignment of ducks (lineup visibility vs detailview visibility)
