### ISSUE TITLE
increase usability for "summary attributes" selection in details tab panel

### ISSUE THREAD

**Issue by ginihumer** [jku-vds-lab/reaction-cime#27]
for numerous features it is currently very tedious to select features that are supposed to be shown in the summary of selected points. thus the usability needs to be improved 

e.g. 
- dialog that shows on the left a list of features that are not shown in the summary and on the right those that are shown; users can drag from left to right; 
- or sth similar to feature selection for embeddings where groups can be selected as one and collapsed

**Comment by ginihumer** [comment]
![image](https://user-images.githubusercontent.com/45741696/151781404-024a41af-d799-4a22-b82f-07ae5dd117b9.png)
example how it looks like currently

**Comment by CursedSeraphim** [comment]
created PR in PSE to merge solution into develop-cime branch as this is a feature that only affects the PSE side
see https://github.com/jku-vds-lab/projection-space-explorer/pull/189

please test whether it works for you as well, if it works merge, and close
