### ISSUE TITLE
compare Old vs. New experiment

### ISSUE THREAD

**Issue by ginihumer** [jku-vds-lab/reaction-cime#3]
e.g. with multiple coordinated view as moritz already started implementing

discuss further details

**Comment by dvmoritzschoefl** [comment]
Discussed with Christina:
side by side view on experiments
selections are synced
rest is own state

**Comment by ginihumer** [comment]
discussed in meeting today. this will be done by DV

additional notes from the meeting:
maybe combine with small multiples and only the two selected ones are shown as interactive visualizations
