### ISSUE TITLE
reference distribution for categorical features

### ISSUE THREAD

**Issue by ginihumer** [jku-vds-lab/reaction-cime#34]
in the coral summary view, categorical features should also have a reference distribution that represents the whole dataset (black line similar to numerical features)

**Comment by CursedSeraphim** [comment]
this is a PSE problem and was addressed in the [PSE repo develop-cime branch](https://github.com/jku-vds-lab/projection-space-explorer/tree/develop-cime) - the last commit for this being d09d9d53f43945d76c4b3b30439bbd339a807d5a

please check whether this is ok and close

**Comment by ginihumer** [comment]
looks good
