### ISSUE TITLE
Label consistency and unification

### ISSUE THREAD

**Issue by ginihumer** [jku-vds-lab/reaction-cime#52]
- use sentence case for all labels
- Feature vs Name (in Projection settings dialog) vs Attributes -> **Feature**
- brightness vs opacity -> **opacity**
- storybook -> group set? or group collection? set of groups?
- storytelling tool -> **group comparison**? compare groups? group differences

anything else that needs to be checked??

**Comment by dvmoritzschoefl** [comment]
Notable mentions: (pr is mh/labels for PSE and Reaction-cime)
- All labels are sentence case
- brightness was renamed to opacity
- Name was renamed to feature
