### ISSUE TITLE
Dataset loading/projection not working as expected

### ISSUE THREAD

**Issue by ginihumer** [jku-vds-lab/reaction-cime#75]
1. go to https://reaction-cime.dev.app.datavisyn.io/
2. upload a new dataset -> dataset is loaded into PSE as expected, but does not show up on the left side where uploaded datasets are shown
3. reload entire page -> still nothing
4. reload page with CTRL+F5 -> now it shows up as expected
same thing happens when deleting a dataset -> it still shows up after normal page reload
also when projecting the newly uploaded dataset, it does not show the projected data after it finished

**Comment by puehringer** [comment]
We disabled the caching of all requests going to /api/..., and this should resolve the issue.
